<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Gibe.Navigation.Umbraco</PackageId>
        <Version>17.0.0</Version>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageTags>Gibe Navigation Umbraco</PackageTags>
        <Authors>Gibe Digital Ltd</Authors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Gibe.Navigation\Gibe.Navigation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Umbraco.Cms.Core" Version="17.5.3" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
      <PackageReference Include="NUnit" Version="4.4.0" />
      <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
      <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
      <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>

</Project>
