<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>Gibe.Navigation.Umbraco</PackageId>
        <Version>10.0.0</Version>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageTags>Gibe Navigation Umbraco</PackageTags>
        <Authors>Gibe Digital Ltd</Authors>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Gibe.Navigation\Gibe.Navigation.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Umbraco.Cms.Core" Version="17.5.3" />
    </ItemGroup>

</Project>
